
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class GridConfig : Luban.BeanBase
    {
        public GridConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            X = _buf.ReadInt();
            Y = _buf.ReadInt();
            PuzzleCount = _buf.ReadInt();
            PrefabPath = _buf.ReadString();
            {int n0 = _buf.ReadSize(); PuzzleList = new System.Collections.Generic.List<puzzle>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { puzzle _e0;  _e0 = global::ET.puzzle.Deserializepuzzle(_buf); PuzzleList.Add(_e0);}}
            {int n0 = _buf.ReadSize(); SlotList = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); SlotList.Add(_e0);}}

            EndInit();
        }

        public static GridConfig DeserializeGridConfig(ByteBuf _buf)
        {
            return new GridConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 名字
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// 行
        /// </summary>
        public readonly int X;
        /// <summary>
        /// 列
        /// </summary>
        public readonly int Y;
        /// <summary>
        /// 拼图数量
        /// </summary>
        public readonly int PuzzleCount;
        /// <summary>
        /// 预制体路径
        /// </summary>
        public readonly string PrefabPath;
        /// <summary>
        /// id
        /// </summary>
        public readonly System.Collections.Generic.List<puzzle> PuzzleList;
        /// <summary>
        /// id
        /// </summary>
        public readonly System.Collections.Generic.List<int> SlotList;
    
        public const int __ID__ = -2067346872;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            foreach (var _e in PuzzleList) { _e?.ResolveRef(); }
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "X:" + X + ","
            + "Y:" + Y + ","
            + "PuzzleCount:" + PuzzleCount + ","
            + "PrefabPath:" + PrefabPath + ","
            + "PuzzleList:" + Luban.StringUtil.CollectionToString(PuzzleList) + ","
            + "SlotList:" + Luban.StringUtil.CollectionToString(SlotList) + ","
            + "}";
        }

        partial void EndRef();
    }

}

