
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class PuzzleConfig : Luban.BeanBase
    {
        public PuzzleConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            X = _buf.ReadInt();
            Y = _buf.ReadInt();
            PrefabPath = _buf.ReadString();
            {int n0 = _buf.ReadSize(); SlotOffset = new System.Collections.Generic.List<System.Collections.Generic.List<int>>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { System.Collections.Generic.List<int> _e0;  {int n1 = _buf.ReadSize(); _e0 = new System.Collections.Generic.List<int>(n1);for(var i1 = 0 ; i1 < n1 ; i1++) { int _e1;  _e1 = _buf.ReadInt(); _e0.Add(_e1);}} SlotOffset.Add(_e0);}}

            EndInit();
        }

        public static PuzzleConfig DeserializePuzzleConfig(ByteBuf _buf)
        {
            return new PuzzleConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 名字
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// x
        /// </summary>
        public readonly int X;
        /// <summary>
        /// y
        /// </summary>
        public readonly int Y;
        /// <summary>
        /// 预制体路径
        /// </summary>
        public readonly string PrefabPath;
        /// <summary>
        /// 偏移量数组
        /// </summary>
        public readonly System.Collections.Generic.List<System.Collections.Generic.List<int>> SlotOffset;
    
        public const int __ID__ = -1306596032;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "X:" + X + ","
            + "Y:" + Y + ","
            + "PrefabPath:" + PrefabPath + ","
            + "SlotOffset:" + Luban.StringUtil.CollectionToString(SlotOffset) + ","
            + "}";
        }

        partial void EndRef();
    }

}

