
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{

    [Config]
    public partial class PuzzleConfigCategory : Singleton<PuzzleConfigCategory>, ILubanConfig
    {
        private readonly Dictionary<int, PuzzleConfig> _dataMap;
        private readonly List<PuzzleConfig> _dataList;
        
        public PuzzleConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, PuzzleConfig>();
            _dataList = new List<PuzzleConfig>();
            
            for(int n = _buf.ReadSize() ; n > 0 ; --n)
            {
                PuzzleConfig _v;
                _v = global::ET.PuzzleConfig.DeserializePuzzleConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }
            EndInit();
        }

        public Dictionary<int, PuzzleConfig> GetAll() => _dataMap;
        public Dictionary<int, PuzzleConfig> DataMap => _dataMap;
        public List<PuzzleConfig> DataList => _dataList;

        public PuzzleConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);

        public PuzzleConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            LubanLog.Error(this,key);
            return default;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
            EndRef();
        }


        partial void EndRef();
    }

}

