
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class puzzle : Luban.BeanBase
    {
        public puzzle(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            Trans = global::ET.gameplay.vec3.Deserializevec3(_buf);

            EndInit();
        }

        public static puzzle Deserializepuzzle(ByteBuf _buf)
        {
            return new puzzle(_buf);
        }

        /// <summary>
        /// Slot预制体ID
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 坐标
        /// </summary>
        public readonly gameplay.vec3 Trans;
    
        public const int __ID__ = -976695234;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            Trans?.ResolveRef();
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Trans:" + Trans + ","
            + "}";
        }

        partial void EndRef();
    }

}

