
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{

    [Config]
    public partial class SlotConfigCategory : Singleton<SlotConfigCategory>, ILubanConfig
    {
        private readonly Dictionary<int, SlotConfig> _dataMap;
        private readonly List<SlotConfig> _dataList;
        
        public SlotConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, SlotConfig>();
            _dataList = new List<SlotConfig>();
            
            for(int n = _buf.ReadSize() ; n > 0 ; --n)
            {
                SlotConfig _v;
                _v = global::ET.SlotConfig.DeserializeSlotConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }
            EndInit();
        }

        public Dictionary<int, SlotConfig> GetAll() => _dataMap;
        public Dictionary<int, SlotConfig> DataMap => _dataMap;
        public List<SlotConfig> DataList => _dataList;

        public SlotConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);

        public SlotConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            LubanLog.Error(this,key);
            return default;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
            EndRef();
        }


        partial void EndRef();
    }

}

