
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET.gameplay
{
    [EnableClass]
    public sealed partial class vec2 : Luban.BeanBase
    {
        public vec2(ByteBuf _buf) 
        {
            X = _buf.ReadFloat();
            Y = _buf.ReadFloat();

            EndInit();
        }

        public static vec2 Deserializevec2(ByteBuf _buf)
        {
            return new gameplay.vec2(_buf);
        }

        /// <summary>
        /// X坐标
        /// </summary>
        public readonly float X;
        /// <summary>
        /// Y坐标
        /// </summary>
        public readonly float Y;
    
        public const int __ID__ = 885439974;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "x:" + X + ","
            + "y:" + Y + ","
            + "}";
        }

        partial void EndRef();
    }

}

