
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{

    [Config]
    public partial class AudioConfigCategory : Singleton<AudioConfigCategory>, ILubanConfig
    {
        private readonly Dictionary<string, AudioConfig> _dataMap;
        private readonly List<AudioConfig> _dataList;
        
        public AudioConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<string, AudioConfig>();
            _dataList = new List<AudioConfig>();
            
            for(int n = _buf.ReadSize() ; n > 0 ; --n)
            {
                AudioConfig _v;
                _v = global::ET.AudioConfig.DeserializeAudioConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.GroupId, _v);
            }
            EndInit();
        }

        public Dictionary<string, AudioConfig> GetAll() => _dataMap;
        public Dictionary<string, AudioConfig> DataMap => _dataMap;
        public List<AudioConfig> DataList => _dataList;

        public AudioConfig GetOrDefault(string key) => _dataMap.GetValueOrDefault(key);

        public AudioConfig Get(string key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            LubanLog.Error(this,key);
            return default;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
            EndRef();
        }


        partial void EndRef();
    }

}

