
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Sirenix.OdinInspector;

namespace ET
{ 
    /// <summary>
    /// 配置表对应的音效名
    /// </summary>
    public enum EAudioKeys
    {
        /// <summary>
        /// 无
        /// </summary>
	    [LabelText("无")]
        None = 0,
        /// <summary>
        /// 登录2DBGM
        /// </summary>
	    [LabelText("登录2DBGM")]
        A2D_Login_Bgm_2D = 1,
    }
} 

