
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{

    [Config]
    public partial class GridConfigCategory : Singleton<GridConfigCategory>, ILubanConfig
    {
        private readonly Dictionary<int, GridConfig> _dataMap;
        private readonly List<GridConfig> _dataList;
        
        public GridConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, GridConfig>();
            _dataList = new List<GridConfig>();
            
            for(int n = _buf.ReadSize() ; n > 0 ; --n)
            {
                GridConfig _v;
                _v = global::ET.GridConfig.DeserializeGridConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }
            EndInit();
        }

        public Dictionary<int, GridConfig> GetAll() => _dataMap;
        public Dictionary<int, GridConfig> DataMap => _dataMap;
        public List<GridConfig> DataList => _dataList;

        public GridConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);

        public GridConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            LubanLog.Error(this,key);
            return default;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
            EndRef();
        }


        partial void EndRef();
    }

}

