
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class SlotConfig : Luban.BeanBase
    {
        public SlotConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            X = _buf.ReadInt();
            Y = _buf.ReadInt();
            PrefabPath = _buf.ReadString();
            AllowPlace = _buf.ReadBool();

            EndInit();
        }

        public static SlotConfig DeserializeSlotConfig(ByteBuf _buf)
        {
            return new SlotConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 名字
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// x
        /// </summary>
        public readonly int X;
        /// <summary>
        /// y
        /// </summary>
        public readonly int Y;
        /// <summary>
        /// 预制体路径
        /// </summary>
        public readonly string PrefabPath;
        /// <summary>
        /// 是否允许放置
        /// </summary>
        public readonly bool AllowPlace;
    
        public const int __ID__ = 1011367680;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "X:" + X + ","
            + "Y:" + Y + ","
            + "PrefabPath:" + PrefabPath + ","
            + "AllowPlace:" + AllowPlace + ","
            + "}";
        }

        partial void EndRef();
    }

}

